
[api]
secret=YR5uuL49YgZZwzWZHrs90SoxapnNaEao
shell.enable=0

[http]
port=80
sslport=443
charSet=utf-8
maxReqCount=1000

[rtmp]
port=1935
sslport=19350

[rtsp]
port=554
sslport=322
auth.enable=0

[rtp]
port=10000

[webrtc]
port=8000
enable=1
; 如需要外网访问，请将 ice_ip 改为宿主机 LAN IP 或公网 IP
; 开发环境用 127.0.0.1 映射到 Docker 宿主机端口
externIP=127.0.0.1
icePort=3478
icePwd=ZLMediaKit
iceTcpPort=3478
iceTransportPolicy=0
iceUfrag=ZLMediaKit
interfaces=
maxRtpCacheMS=5000
maxRtpCacheSize=2048
max_bitrate=0
max_stun_retry=7
min_bitrate=0
nackAudioRtpSize=4
nackIntervalRatio=1.000000
nackMaxCount=15
nackMaxMS=3000
nackMaxSize=2048
nackRtpSize=8
port=8000
port_range=49152-65535
preferredCodecA=PCMA,PCMU,opus,mpeg4-generic
preferredCodecV=H264,H265,AV1,VP9,VP8
preferred_tcp=0
rembBitRate=0
signalingPort=3000
signalingSslPort=3001
start_bitrate=0
tcpPort=8000
timeoutSec=15

[rtmp]
directProxy=1
enhanced=1
handshakeSecond=15
keepAliveSecond=15

[rtp]
audioMtuSize=600
h264_stap_a=1
lowLatency=0
rtpMaxSize=10
videoMtuSize=1400

[rtp_proxy]
dumpDir=
gop_cache=1
h264_pt=98
h265_pt=99
merge_frame=1
opus_pt=100
port=10000
port_range=30000-35000
ps_pt=96
rtp_g711_dur_ms=100
timeoutSec=15
udp_recv_socket_buffer=4194304

[rtsp]
authBasic=0
directProxy=1
handshakeSecond=15
keepAliveSecond=15
lowLatency=0
rtpTransportType=-1

[shell]
maxReqSize=1024
port=9000

[srt]
latencyMul=4
passPhrase=
pktBufSize=8192
port=9000
timeoutSec=5

[rtc]
externIP=127.0.0.1
preferred_tcp=1

[hook]
on_record_mp4=http://host.docker.internal:8001/api/v1/video/record/webhook/on_record_mp4

[general]
record_path = ./www/record

