export * from "./core/types";
export { default as AnnotationWorkbench } from "./core/AnnotationWorkbench.vue";
export { detectionPlugin } from "./tasks/detection";
export { rotatedBoxPlugin } from "./tasks/rotatedBox";
export { segmentationPlugin } from "./tasks/segmentation";
export { keypointPlugin } from "./tasks/keypoint";
export { ocrPlugin } from "./tasks/ocr";
export { classificationPlugin } from "./tasks/classification";
export { useAnnotationCanvas } from "./core/useAnnotationCanvas";
export { useAnnotationStore } from "./core/useAnnotationStore";
