"""迁移脚本

Revision ID: 2e9f6ccd3ff4
Revises: a923822e9bef
Create Date: 2026-05-27 11:32:15.424593

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e9f6ccd3ff4'
down_revision: str | None = 'a923822e9bef'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_apscheduler_jobs_next_run_time', table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.add_column('video_layouts', sa.Column('is_template', sa.Boolean(), nullable=False, server_default='false', comment='是否模板'))
    op.alter_column('video_layouts', 'is_template', server_default=None)
    op.add_column('video_layouts', sa.Column('patrol_interval', sa.Integer(), nullable=True, comment='轮巡间隔(秒)'))
    op.alter_column('video_layouts', 'description',
               existing_type=sa.TEXT(),
               comment='描述',
               existing_comment='备注/描述',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video_layouts', 'description',
               existing_type=sa.TEXT(),
               comment='备注/描述',
               existing_comment='描述',
               existing_nullable=True)
    op.drop_column('video_layouts', 'patrol_interval')
    op.drop_column('video_layouts', 'is_template')
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='apscheduler_jobs_pkey')
    )
    op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###
