"""迁移脚本

Revision ID: 38d18b9077de
Revises: 2e9f6ccd3ff4
Create Date: 2026-05-27 11:42:10.323771

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '38d18b9077de'
down_revision: str | None = '2e9f6ccd3ff4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _column_names(table: str) -> set[str]:
    """返回表的现有列名集合；表不存在时返回空集（兼容空库重放与兜底补列）。"""
    insp = sa.inspect(op.get_bind())
    if not insp.has_table(table):
        return set()
    return {col["name"] for col in insp.get_columns(table)}


def _drop_apscheduler_jobs() -> None:
    """幂等删除历史遗留的 ``apscheduler_jobs``（base 迁移从未创建该表）。"""
    insp = sa.inspect(op.get_bind())
    if not insp.has_table("apscheduler_jobs"):
        return
    index_names = {idx["name"] for idx in insp.get_indexes("apscheduler_jobs")}
    if "ix_apscheduler_jobs_next_run_time" in index_names:
        op.drop_index("ix_apscheduler_jobs_next_run_time", table_name="apscheduler_jobs")
    op.drop_table("apscheduler_jobs")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 历史遗留表：仅旧库存在，空库重放时必须跳过
    _drop_apscheduler_jobs()
    # param_meta 可能已由启动兜底补列添加（重启优先路径），故先探测
    if 'param_meta' not in _column_names('video_algorithms'):
        op.add_column('video_algorithms', sa.Column('param_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='参数元数据定义（标签、类型、选项、单位、说明等）'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_algorithms', 'param_meta')
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='apscheduler_jobs_pkey')
    )
    op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###
