"""迁移脚本

Revision ID: a923822e9bef
Revises: 0dfa7af72c50
Create Date: 2026-05-24 20:29:54.380173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a923822e9bef'
down_revision: Union[str, None] = '0dfa7af72c50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_apscheduler_jobs_next_run_time', table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.alter_column('video_algorithm_tasks', 'runtime_overrides',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='运行时参数覆盖值',
               existing_nullable=True)
    op.alter_column('video_algorithm_tasks', 'params_overrides',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='算法参数覆盖值（针对该布控点位调整阈值等）',
               existing_nullable=True)
    op.alter_column('video_algorithms', 'model_file_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='模型配置（格式、加密密钥、解密参数等）',
               existing_nullable=True)
    op.alter_column('video_algorithms', 'runtime_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='运行时配置（推理引擎、GPU、线程数、批处理大小等）',
               existing_nullable=True)
    op.alter_column('video_algorithms', 'preset_params',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='预设算法参数（按算法类型动态定义，如置信度阈值、人数上限等）',
               existing_nullable=True)
    op.alter_column('video_algorithms', 'output_schema',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='输出数据格式（绘制框、标签、颜色等）',
               existing_comment='输出数据格式',
               existing_nullable=True)
    op.drop_column('video_algorithms', 'model_config')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_algorithms', sa.Column('model_config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.alter_column('video_algorithms', 'output_schema',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='输出数据格式',
               existing_comment='输出数据格式（绘制框、标签、颜色等）',
               existing_nullable=True)
    op.alter_column('video_algorithms', 'preset_params',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='预设算法参数（按算法类型动态定义，如置信度阈值、人数上限等）',
               existing_nullable=True)
    op.alter_column('video_algorithms', 'runtime_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='运行时配置（推理引擎、GPU、线程数、批处理大小等）',
               existing_nullable=True)
    op.alter_column('video_algorithms', 'model_file_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='模型配置（格式、加密密钥、解密参数等）',
               existing_nullable=True)
    op.alter_column('video_algorithm_tasks', 'params_overrides',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='算法参数覆盖值（针对该布控点位调整阈值等）',
               existing_nullable=True)
    op.alter_column('video_algorithm_tasks', 'runtime_overrides',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='运行时参数覆盖值',
               existing_nullable=True)
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='apscheduler_jobs_pkey')
    )
    op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###
