"""迁移脚本

Revision ID: a923822e9bef
Revises: 0dfa7af72c50
Create Date: 2026-05-24 20:29:54.380173

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a923822e9bef'
down_revision: str | None = '0dfa7af72c50'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _column_names(table: str) -> set[str]:
    """返回表的现有列名集合；表不存在时返回空集。

    空库重放（base 迁移）不会创建 ``runtime_overrides`` 等列，因此所有
    针对列的 alter/drop 都必须先探测，避免 ``UndefinedColumn`` 中断整条链。
    """
    insp = sa.inspect(op.get_bind())
    if not insp.has_table(table):
        return set()
    return {col["name"] for col in insp.get_columns(table)}


def _drop_apscheduler_jobs() -> None:
    """幂等删除历史遗留的 ``apscheduler_jobs``（base 迁移从未创建该表）。"""
    insp = sa.inspect(op.get_bind())
    if not insp.has_table("apscheduler_jobs"):
        return
    index_names = {idx["name"] for idx in insp.get_indexes("apscheduler_jobs")}
    if "ix_apscheduler_jobs_next_run_time" in index_names:
        op.drop_index("ix_apscheduler_jobs_next_run_time", table_name="apscheduler_jobs")
    op.drop_table("apscheduler_jobs")


def _sync_comment(
    table: str,
    column: str,
    comment: str,
    *,
    existing_comment: str | None = None,
) -> None:
    """仅在列存在时同步注释（列由后续迁移/兜底补列创建，此处保持幂等）。"""
    if column not in _column_names(table):
        return
    op.alter_column(
        table,
        column,
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment=comment,
        existing_comment=existing_comment,
        existing_nullable=True,
    )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 历史遗留表：仅旧库存在，空库重放时必须跳过
    _drop_apscheduler_jobs()
    # 以下列在 base 迁移中并不存在（后续迁移/兜底补列才创建），逐列探测再同步注释
    _sync_comment('video_algorithm_tasks', 'runtime_overrides', '运行时参数覆盖值')
    _sync_comment('video_algorithm_tasks', 'params_overrides', '算法参数覆盖值（针对该布控点位调整阈值等）')
    _sync_comment('video_algorithms', 'model_file_config', '模型配置（格式、加密密钥、解密参数等）')
    _sync_comment('video_algorithms', 'runtime_config', '运行时配置（推理引擎、GPU、线程数、批处理大小等）')
    _sync_comment('video_algorithms', 'preset_params', '预设算法参数（按算法类型动态定义，如置信度阈值、人数上限等）')
    _sync_comment('video_algorithms', 'output_schema', '输出数据格式（绘制框、标签、颜色等）', existing_comment='输出数据格式')
    if 'model_config' in _column_names('video_algorithms'):
        op.drop_column('video_algorithms', 'model_config')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_algorithms', sa.Column('model_config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.alter_column('video_algorithms', 'output_schema',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='输出数据格式',
               existing_comment='输出数据格式（绘制框、标签、颜色等）',
               existing_nullable=True)
    op.alter_column('video_algorithms', 'preset_params',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='预设算法参数（按算法类型动态定义，如置信度阈值、人数上限等）',
               existing_nullable=True)
    op.alter_column('video_algorithms', 'runtime_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='运行时配置（推理引擎、GPU、线程数、批处理大小等）',
               existing_nullable=True)
    op.alter_column('video_algorithms', 'model_file_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='模型配置（格式、加密密钥、解密参数等）',
               existing_nullable=True)
    op.alter_column('video_algorithm_tasks', 'params_overrides',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='算法参数覆盖值（针对该布控点位调整阈值等）',
               existing_nullable=True)
    op.alter_column('video_algorithm_tasks', 'runtime_overrides',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='运行时参数覆盖值',
               existing_nullable=True)
    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='apscheduler_jobs_pkey')
    )
    op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###
