"""迁移脚本

Revision ID: b744384adf6f
Revises: 38d18b9077de
Create Date: 2026-07-04 16:02:56.521743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b744384adf6f'
down_revision: Union[str, None] = '38d18b9077de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('train_evals',
    sa.Column('model_repo_id', sa.Integer(), nullable=False, comment='模型版本ID'),
    sa.Column('eval_dataset_id', sa.Integer(), nullable=False, comment='评估数据集ID'),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='评估指标'),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', 'CANCELLED', name='trainstatus'), nullable=False, comment='状态'),
    sa.Column('log', sa.Text(), nullable=True, comment='评估日志'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('uuid', sa.String(length=64), nullable=False, comment='UUID全局唯一标识'),
    sa.Column('description', sa.Text(), nullable=True, comment='备注/描述'),
    sa.Column('created_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否已删除(0:未删除 1:已删除)'),
    sa.Column('deleted_time', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('created_id', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('updated_id', sa.Integer(), nullable=True, comment='更新人ID'),
    sa.Column('deleted_id', sa.Integer(), nullable=True, comment='删除人ID'),
    sa.ForeignKeyConstraint(['created_id'], ['sys_user.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_id'], ['sys_user.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_id'], ['sys_user.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_train_evals_created_id'), 'train_evals', ['created_id'], unique=False)
    op.create_index(op.f('ix_train_evals_created_time'), 'train_evals', ['created_time'], unique=False)
    op.create_index(op.f('ix_train_evals_deleted_id'), 'train_evals', ['deleted_id'], unique=False)
    op.create_index(op.f('ix_train_evals_deleted_time'), 'train_evals', ['deleted_time'], unique=False)
    op.create_index(op.f('ix_train_evals_id'), 'train_evals', ['id'], unique=False)
    op.create_index(op.f('ix_train_evals_is_deleted'), 'train_evals', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_train_evals_updated_id'), 'train_evals', ['updated_id'], unique=False)
    op.create_index(op.f('ix_train_evals_updated_time'), 'train_evals', ['updated_time'], unique=False)
    op.create_index(op.f('ix_train_evals_uuid'), 'train_evals', ['uuid'], unique=True)
    op.create_table('train_models',
    sa.Column('name', sa.String(length=128), nullable=False, comment='模型名称'),
    sa.Column('framework', sa.Enum('PADDLEX', 'ULTRALYTICS', name='trainframework'), nullable=False, comment='训练框架'),
    sa.Column('version', sa.String(length=32), nullable=False, comment='语义版本号'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('storage_path', sa.String(length=512), nullable=True, comment='RustFS 存储路径'),
    sa.Column('format', sa.String(length=32), nullable=True, comment='导出格式 ONNX/Paddle/TorchScript'),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='评估指标'),
    sa.Column('annotation_dataset_id', sa.Integer(), nullable=True, comment='来源数据集ID'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='draft/released/archived'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('uuid', sa.String(length=64), nullable=False, comment='UUID全局唯一标识'),
    sa.Column('created_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否已删除(0:未删除 1:已删除)'),
    sa.Column('deleted_time', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('created_id', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('updated_id', sa.Integer(), nullable=True, comment='更新人ID'),
    sa.Column('deleted_id', sa.Integer(), nullable=True, comment='删除人ID'),
    sa.ForeignKeyConstraint(['created_id'], ['sys_user.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_id'], ['sys_user.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_id'], ['sys_user.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_train_models_created_id'), 'train_models', ['created_id'], unique=False)
    op.create_index(op.f('ix_train_models_created_time'), 'train_models', ['created_time'], unique=False)
    op.create_index(op.f('ix_train_models_deleted_id'), 'train_models', ['deleted_id'], unique=False)
    op.create_index(op.f('ix_train_models_deleted_time'), 'train_models', ['deleted_time'], unique=False)
    op.create_index(op.f('ix_train_models_id'), 'train_models', ['id'], unique=False)
    op.create_index(op.f('ix_train_models_is_deleted'), 'train_models', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_train_models_updated_id'), 'train_models', ['updated_id'], unique=False)
    op.create_index(op.f('ix_train_models_updated_time'), 'train_models', ['updated_time'], unique=False)
    op.create_index(op.f('ix_train_models_uuid'), 'train_models', ['uuid'], unique=True)
    op.create_table('train_tasks',
    sa.Column('name', sa.String(length=128), nullable=False, comment='任务名称'),
    sa.Column('framework', sa.Enum('PADDLEX', 'ULTRALYTICS', name='trainframework'), nullable=False, comment='训练框架'),
    sa.Column('dataset_id', sa.Integer(), nullable=False, comment='数据集ID'),
    sa.Column('model_repo_id', sa.Integer(), nullable=True, comment='产出模型ID'),
    sa.Column('base_model_id', sa.Integer(), nullable=True, comment='基础模型ID'),
    sa.Column('docker_image', sa.String(length=256), nullable=False, comment='Docker 镜像'),
    sa.Column('hyperparams', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='超参数'),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', 'CANCELLED', name='trainstatus'), nullable=False, comment='状态'),
    sa.Column('progress', sa.Integer(), nullable=False, comment='进度0-100'),
    sa.Column('error_log', sa.Text(), nullable=True, comment='错误日志'),
    sa.Column('started_at', sa.DateTime(), nullable=True, comment='开始时间'),
    sa.Column('finished_at', sa.DateTime(), nullable=True, comment='完成时间'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('uuid', sa.String(length=64), nullable=False, comment='UUID全局唯一标识'),
    sa.Column('description', sa.Text(), nullable=True, comment='备注/描述'),
    sa.Column('created_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否已删除(0:未删除 1:已删除)'),
    sa.Column('deleted_time', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('created_id', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('updated_id', sa.Integer(), nullable=True, comment='更新人ID'),
    sa.Column('deleted_id', sa.Integer(), nullable=True, comment='删除人ID'),
    sa.ForeignKeyConstraint(['created_id'], ['sys_user.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_id'], ['sys_user.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_id'], ['sys_user.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_train_tasks_created_id'), 'train_tasks', ['created_id'], unique=False)
    op.create_index(op.f('ix_train_tasks_created_time'), 'train_tasks', ['created_time'], unique=False)
    op.create_index(op.f('ix_train_tasks_deleted_id'), 'train_tasks', ['deleted_id'], unique=False)
    op.create_index(op.f('ix_train_tasks_deleted_time'), 'train_tasks', ['deleted_time'], unique=False)
    op.create_index(op.f('ix_train_tasks_id'), 'train_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_train_tasks_is_deleted'), 'train_tasks', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_train_tasks_updated_id'), 'train_tasks', ['updated_id'], unique=False)
    op.create_index(op.f('ix_train_tasks_updated_time'), 'train_tasks', ['updated_time'], unique=False)
    op.create_index(op.f('ix_train_tasks_uuid'), 'train_tasks', ['uuid'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_train_tasks_uuid'), table_name='train_tasks')
    op.drop_index(op.f('ix_train_tasks_updated_time'), table_name='train_tasks')
    op.drop_index(op.f('ix_train_tasks_updated_id'), table_name='train_tasks')
    op.drop_index(op.f('ix_train_tasks_is_deleted'), table_name='train_tasks')
    op.drop_index(op.f('ix_train_tasks_id'), table_name='train_tasks')
    op.drop_index(op.f('ix_train_tasks_deleted_time'), table_name='train_tasks')
    op.drop_index(op.f('ix_train_tasks_deleted_id'), table_name='train_tasks')
    op.drop_index(op.f('ix_train_tasks_created_time'), table_name='train_tasks')
    op.drop_index(op.f('ix_train_tasks_created_id'), table_name='train_tasks')
    op.drop_table('train_tasks')
    op.drop_index(op.f('ix_train_models_uuid'), table_name='train_models')
    op.drop_index(op.f('ix_train_models_updated_time'), table_name='train_models')
    op.drop_index(op.f('ix_train_models_updated_id'), table_name='train_models')
    op.drop_index(op.f('ix_train_models_is_deleted'), table_name='train_models')
    op.drop_index(op.f('ix_train_models_id'), table_name='train_models')
    op.drop_index(op.f('ix_train_models_deleted_time'), table_name='train_models')
    op.drop_index(op.f('ix_train_models_deleted_id'), table_name='train_models')
    op.drop_index(op.f('ix_train_models_created_time'), table_name='train_models')
    op.drop_index(op.f('ix_train_models_created_id'), table_name='train_models')
    op.drop_table('train_models')
    op.drop_index(op.f('ix_train_evals_uuid'), table_name='train_evals')
    op.drop_index(op.f('ix_train_evals_updated_time'), table_name='train_evals')
    op.drop_index(op.f('ix_train_evals_updated_id'), table_name='train_evals')
    op.drop_index(op.f('ix_train_evals_is_deleted'), table_name='train_evals')
    op.drop_index(op.f('ix_train_evals_id'), table_name='train_evals')
    op.drop_index(op.f('ix_train_evals_deleted_time'), table_name='train_evals')
    op.drop_index(op.f('ix_train_evals_deleted_id'), table_name='train_evals')
    op.drop_index(op.f('ix_train_evals_created_time'), table_name='train_evals')
    op.drop_index(op.f('ix_train_evals_created_id'), table_name='train_evals')
    op.drop_table('train_evals')
    # ### end Alembic commands ###
